### ISSUE TITLE
Allow for multiple tooltips to be shown

### ISSUE THREAD

**Issue by Enriath** [ryanxie0/lingering-click-tooltips#3]
When clicking rapidly without anchor tooltips enabled, the older tooltips get jarringly destroyed for the newest one. It would be great to be able to see all the recent clicks that would have been present

**Comment by ryanxie0** [comment]
This was something I actually had during initial development of the plugin, but the implementation of it used a package imported from Google's namespace. I've been told that lots of Google's packages quickly become deprecated because their developers create lots of packages and the company doesn't bother to maintain them after the developer leaves (which happens a lot, lol).

This combined with the consideration that I believe most users won't want more than 1 tooltip showing at any given time led me to eventually take the feature out later. It just seemed like a lot of screen clutter.

But I'll probably put it back in later after I find a clean way to do it without using Google packages.

**Comment by ryanxie0** [comment]
The update to v1.1 includes the ability to show multiple tooltips.
