### ISSUE TITLE
Allow tooltips to go to a fixed position instead of at the object

### ISSUE THREAD

**Issue by orlp** [ryanxie0/lingering-click-tooltips#5]
I think it would be neat if it were possible to place the tooltip at a fixed position of the screen, rather than at the objects position.

If this is done there should also probably be an option for whether the tooltip grows towards the left or towards the right, if you wish to place the tooltip into one of the corners.

**Comment by ryanxie0** [comment]
When you say grows towards the left or towards the right, are you referring to the alignment of the text? If so, that should be feasible.

As of writing this, I have a working panel component that simply displays the text that would have otherwise been rendered as a tooltip. Like most other overlay components offered by RuneLite, it can be repositioned by holding the alt key and dragging it around.

I'll continue to polish this out. In the meantime, suggest anything else you can think of.

**Comment by orlp** [comment]
> When you say grows towards the left or towards the right, are you referring to the alignment of the text? 

Yes, if I wanted to position this on the right corner, I'd want the text to be right-aligned, and vice versa on a left corner. Maybe allow centered text as well.

> As of writing this, I have a working panel component that simply displays the text that would have otherwise been rendered as a tooltip. Like most other overlay components offered by RuneLite, it can be repositioned by holding the alt key and dragging it around.

Yes, something like that. Although I think I would prefer the aesthetics of a tooltip, but an alt-draggable anchor for it would be a good idea.

**Comment by ryanxie0** [comment]
After a bit more experimentation, I've decided not to use the panel component for rendering at a fixed position. It's not exactly necessary for what's needed. For now, the fixed position only shows the most recent action and it always shows unless you double-tap CTRL to hide. I may need to reintroduce the panel component if I decide to allow multiple tooltips showing with the fixed position, but I'll deal with that when/if I get to it.

I'm capable of just using the same component used to render the tooltips. I suppose that means the aesthetics won't change. Something to note is that the tooltip components won't need to worry about text alignment because the background resizes itself to fit the text. There's no wrapping involved, but I highly doubt it's necessary.

I'm seeing a weird issue where the background color is rendering as opaque for fixed position tooltips only, even if there is an alpha value for the color. Can't seem to figure out why it's doing that, but it really bothers me. If I can't figure it out I'll just have to fix it on the next update. The coming update 1.2 has a lot of other features and I don't want to hold off on all those for this.

**Comment by ryanxie0** [comment]
Of course only moments after posting a comment stating I have a mysterious bug I figure out the issue.

The background color was opaque because I was setting the alpha incorrectly on something else during rendering.

**Comment by orlp** [comment]
> For now, the fixed position only shows the most recent action and it always shows unless you double-tap CTRL to hide.

Is there any reason it doesn't respect the already existing duration settings? I don't want it always shown, just a flash on a click.

> Something to note is that the tooltip components won't need to worry about text alignment because the background resizes itself to fit the text. There's no wrapping involved, but I highly doubt it's necessary.

That's not true. If you want the tooltip in the right corner, the text must be right-aligned so the tooltip doesn't go off the screen. Similarly, if you want the tooltip in the left corner, the text must be left-aligned so the tooltip doesn't go off the screen.

An alternative is to have a right anchor or a left anchor for the tooltip, first render the whole tooltip and compute its width, and then place it according to the anchor.

**Comment by ryanxie0** [comment]
I had it stick around because if they disappear, you'd have to turn on the permanent setting whenever you wanted to move the component. But I just realized I can have them continue to render after becoming transparent so that you can see the outline of the tooltip when holding alt even after it's gone.

What you're talking about isn't text alignment anymore. It sounds more like a graphical component alignment to me. Regardless of what we call it, I definitely see your point about how the component needs to fit snugly in a corner. The components used to render the tooltips treat their upper left corner as origin, so I might need to do some more possibly annoying legwork to have the rendering basically treat the right side as origin.

At the moment, there does seem to be component alignment if you happen to place the fixed tooltips into one of the six zones that you can basically "attach" overlay components to. Even though those zones are somewhat limited, I wouldn't think anyone would want to have the tooltips appear over their other widgets (like the minimap or chatbox), so I'm gonna consider that good enough for now. Like I said, I don't want to delay 1.2 any longer than I have to for this. But I already have more ideas for a 1.3 update and a QoL update like that to the fixed location can be included with those.

**Comment by orlp** [comment]
> What you're talking about isn't text alignment anymore. It sounds more like a graphical component alignment to me. Regardless of what we call it, I definitely see your point about how the component needs to fit snugly in a corner.

Fair enough, we're talking on the same wavelength then :)

> The components used to render the tooltips treat their upper left corner as origin, so I might need to do some more possibly annoying legwork to have the rendering basically treat the right side as origin.

If it's possible to move it after it has rendered, and you can get the rendered length you can use that to offset it.

**Comment by ryanxie0** [comment]
The update to v1.2 includes fixed location rendering for tooltips. It doesn't include the component alignment requested here, which is being considered for future updates.

**Comment by ryanxie0** [comment]
I tried my hand at implementing component alignment, it doesn't seem like it's going to work. Basically what I discovered is that the position of overlay components is treated as a relative translation of the overlay's preferredLocation value. When I move a component after it's rendered, the overlay bounds (the rectangle that defines the position/dimension of your Overlay class) do not follow it. Essentially what ends up happening is that when you align the component to be centered or right-aligned, you'll see the overlay outline in its original position while your overlay component ends up way off to the left. So alignment works, but holding the alt key and seeing the bounds over thin air looks wrong.

This doesn't seem like something I can control either. The only thing that ends up determining the bounds of your overlay is the overlay's preferredLocation (which we don't want to modify unless we want the overlay to slide further and further left each time we align a component center or right) and the dimensions you return in your render method. You can set your overlay bounds all you like, but when it comes time to render, the rendering code will ignore/override your value. You can probably see what I'm talking about if you dig your way through the overlay rendering code managed by the RuneLite team (be warned, it's a TON).

If you look through the overlay code you'll see that I'm already doing this for other tooltips. The clamping code renders an invisible component to obtain its dimensions, then adjusts the component's location and re-renders. But this doesn't matter because those tooltips are either anchored or lingering for which my render method is returning null. In those cases the overlay bounds isn't needed.

What bothers me is that alignment without the bounds being off is working when you put the fixed tooltips into one of those six overlay zones. So the overlay rendering code has something aligning components without messing up the bounds, but I can't seem to emulate that when your fixed tooltip is rendering somewhere else.

I think the alignment you get from those attachment zones is good enough for all intents and purposes.
